const BASE_QUESTIONS = [
  { question: "校长（大学）", score: 1 },
  { question: "校长（中小学）", score: 1 },
  { question: "副省长", score: 1 },
  { question: "三好学生", score: 1 },
  { question: "助理教授", score: 1 },
  { question: "三十年河东三十年河西。", score: 2 },
  { question: "有朋自远方来，不亦乐乎", score: 2 },
  { question: "物以类聚人以群分", score: 2 },
  { question: "冤家宜解不宜结", score: 2 },
  { question: "有缘千里来相会", score: 2 },
  { question: "同舟共济", score: 2 },
  { question: "保时捷", score: 0.5 },
  { question: "梅赛德斯奔驰", score: 0.5 },
  { question: "阿迪达斯", score: 0.5 },
  { question: "卡地亚", score: 0.5 },
  { question: "倒打一耙", score: 2 },
  { question: "现在世界上有人给中国戴很多高帽子", score: 2 },
  {
    question:
      "近百年来，为了摆脱半殖民半封建的历史境遇，中国人民进行了艰苦卓绝、奋发图强的斗争。",
    score: 3,
  },
  { question: "关心和支持中国现代化建设的外国友人", score: 3 },
  { question: "如果关门了，那可不是大吉，老百姓生活都会受到影响", score: 3 },
  {
    question:
      "最近几年大批农民工涌入大城市，因为他们在那里可以找到不错的工作并且养活家人。",
    score: 3,
  },
  {
    question:
      "2020年7月24日上午, 中国外交部通知美国驻华使馆，中方决定撤销对美国驻成都总领事馆的设立和运行许可。",
    score: 4,
  },
  { question: "尽收眼底", score: 2 },
  { question: "古建筑群", score: 2 },
  { question: "退思园", score: 1 },
  { question: "它是中国五A级旅游景区。", score: 2 },
  { question: "葱烧海参", score: 2 },
  { question: "简述麻婆豆腐以及它的故事", score: 4 },
  { question: "山药当归枸杞", score: 3 },
  { question: "油条", score: 2 },
  {
    question: "四川人，有的吃了辣椒不上火，换一个地方的人吃了辣椒，他上火了。",
    score: 3,
  },
]

const NEW_QUESTIONS = [
  { question: "历史悠久的文化古迹", score: 2 },
  { question: "人间天堂", score: 2 },
  { question: "莫欺少年穷", score: 2 },
  { question: "说曹操曹操到", score: 2 },
  { question: "给中国戴高帽子", score: 2 },
  { question: "最严峻的考验", score: 2 },
  { question: "百花齐放", score: 2 },
  { question: "崇山峻岭", score: 2 },
  { question: "自卑情节", score: 2 },
  { question: "军工综合企业", score: 2 },
  { question: "讲文明、文明素质、社会文明、文明历史", score: 3 },
  { question: "实现中华民族伟大复兴", score: 3 },
  { question: "留得青山在不怕没柴烧", score: 2 },
  { question: "你一句春不晚我便到了真江南", score: 3 },
  { question: "天下没有不散的筵席", score: 2 },
  { question: "祝友谊长存", score: 1 },
  { question: "一路顺风", score: 1 },
  { question: "今夕不同往日", score: 2 },
  { question: "新质生产力", score: 3 },
  { question: "全面建设社会主义现代化国家", score: 4 },
  { question: "孔子学院", score: 2 },
  { question: "四大文明古国", score: 2 },
  { question: "社会文明程度", score: 3 },
  { question: "姹紫嫣红", score: 2 },
  { question: "中国外交部", score: 2 },
  { question: "中国驻墨尔本总领事馆", score: 3 },
  { question: "美国驻华使馆", score: 3 },
  { question: "干炒牛河", score: 1 },
  { question: "黄焖鸡米饭", score: 1 },
  { question: "红烧肉", score: 1 },
  { question: "白切鸡", score: 1 },
  { question: "炒栗子", score: 1 },
  { question: "深烘/中烘/浅烘", score: 2 },
  { question: "饕餮贵族", score: 2 },
  { question: "清淡除湿的食物", score: 2 },
  { question: "温阳散寒", score: 2 },
  { question: "生津润肺", score: 2 },
  { question: "百年修得同船渡千年修得共枕眠", score: 3 },
  { question: "己所不欲，勿施于人", score: 2 },
  { question: "中国古代文明的发展是中华民族奋斗、自强的结果。", score: 4 },
  { question: "近百年来，中国人为了摆脱屈辱历史而奋斗。", score: 4 },
  { question: "民族振兴", score: 3 },
  { question: "关心现代化建设", score: 3 },
  { question: "和气生财", score: 2 },
  { question: "金无足赤人无完人", score: 2 },
  { question: "和谐共存", score: 2 },
  { question: "生态文明建设", score: 3 },
  { question: "交流互鉴", score: 3 },
  { question: "进行斗争", score: 3 },
  { question: "历史境遇", score: 3 },
  { question: "自强不息", score: 2 },
  { question: "商业伙伴", score: 2 },
  { question: "产生丰硕成果", score: 3 },
  { question: "不到长城非好汉", score: 2 },
  { question: "人人都有出头日", score: 2 },
  { question: "各位代表", score: 1 },
  { question: "台湾问题", score: 4 },
  { question: "不平凡的第一年", score: 3 },
  { question: "复杂严峻形势", score: 3 },
  { question: "公民文明素质和社会文明程度", score: 3 },
  { question: "爱国情怀", score: 3 },
  { question: "外交失误", score: 3 },
  { question: "头破血流", score: 2 },
  { question: "出界", score: 1 },
  { question: "太湖三白", score: 2 },
  { question: "同床异梦", score: 2 },
  { question: "求同存异", score: 2 },
  { question: "和而不同", score: 2 },
  { question: "外交官", score: 2 },
  { question: "大使", score: 2 },
  { question: "专访", score: 2 },
  { question: "公共外交", score: 3 },
  { question: "外交政策", score: 3 },
  { question: "多边关系", score: 3 },
  { question: "中西对话", score: 3 },
  { question: "国际形象", score: 3 },
  { question: "国家荣誉", score: 3 },
  { question: "文化交流", score: 3 },
  { question: "高压采访", score: 2 },
  { question: "实时翻译", score: 2 },
  { question: "即席口译", score: 3 },
  { question: "新闻发布会", score: 3 },
  { question: "政府工作报告", score: 3 },
  { question: "同胞", score: 1 },
  { question: "大陆与台湾", score: 3 },
  { question: "爱国热情和奋斗精神", score: 3 },
  { question: "融合传统与现代", score: 3 },
]

export default [...BASE_QUESTIONS, ...NEW_QUESTIONS]
